### ISSUE TITLE
Importing Scratch from several repositories causes several compilation of it

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/vpack#23]
For example, if we use scratch in `abu-dhabi`, and also in `player`, weird things happen on compilation.

It compiles two times and on the Scratch from player, which does not have any options on top uses default colors, sizes, etc. It acts like it's two different things, while even versions of them are the same.

screenshots: http://cl.ly/3S210S002q2F, http://cl.ly/092U3Q391Z1a

**Comment by DanilloCorvalan** [comment]
@nikoloza can you run `vpack -v` ?  Do I only need to pull ADM in order to reproduce it ?

**Comment by DanilloCorvalan** [comment]
@nikoloza @youzi I think I found the problem, less doesn't import only once checking the file path, so we need to stick to a single path in order to avoid duplication:

This is the correct way of importing:
`@import "~vigour-scratch/index.less";`

But on player I can see two ways of doing so, the other one is like:
`@import "../node_modules/vigour-scratch/index.less";`

Let's stick with the first one :)
Could you guys check if that solves the problem ?

regarding the issue on less repo:
https://github.com/less/less.js/issues/49

**Comment by youzi** [comment]
@DanilloCorvalan This doesn't solve the issue it seems, as I am already doing this. Please try sbsnew#develop (don't forget npm i)

**Comment by DanilloCorvalan** [comment]
Possible options:
 - Whenever we want to use variables and mixins we can import the less file as a reference using `@import (reference) "~vigour-scratch/index.less"` [nice link about it here](https://css-tricks.com/reference-imports-in-less-are-kinda-cool/)
 - **Do not** require less files through js files, although this looks the right way working with independent components, there is no way less can know what is being referenced by javascript and what is being referenced by other less files. In other words 1 require of a less file should compile the less files all the way down to components and their dependencies.

**Comment by nikoloza** [comment]
So, the way I fixed it is like that: 
1. require all local less files for player in one entry point (https://github.com/vigour-io/player/blob/2c6d9c4f6dba8649a9259d963c9d2c692b9f193e/lib/style.less).
2. require player less file from project less imports (https://github.com/vigour-io/sbs/blob/f651d11ece7db7e6be17c0f13e4ac476dd62ed44/less/vier/imports.less#L8).

@DanilloCorvalan @youzi reference is not a solution, because when it uses mixins, variables and compiles them, it does not apply project specific settings and use default ones.

This fix prevents using scratch into player, so this is temporary fix until we find out the best way.

**Comment by jimdebeer** [comment]
I think we can decouple the less from js completely (we already did that everywhere)
the only thing we need to to use a map of import files (and never require/import them double!) what you probably need to do is create a correct order of the less files based on a dependency map of the less import statement (if you want to be ultra sure) this is by default provided by less, but also pretty easy to make  @nikoloza I may be wrong here but is this whats needed?

**Comment by nikoloza** [comment]
@jimdebeer if I get it correctly we have that already implemented what you meant (?)

https://github.com/vigour-io/play/blob/develop/lib/style.less

**Comment by DanilloCorvalan** [comment]
@nikoloza @jimdebeer so the problem was that on `player` it was requiring `require('index.less')` and this less file imports scratch. When doing that less loader runs again, separate from the one running on the end project (e.g.: ADM) so we have the duplications of styles. @nikoloza can you test removing all the requires of less files from the player, it will probably work but requires us to import it from the end project.

@jimdebeer less already uses lazy load so it doesn't matter the order I think.

**Comment by nikoloza** [comment]
@DanilloCorvalan I disabled all this requires inside javascript. branch on player: `feature/less-imports`

But even if I import Scratch from Less in the player, it duplicates it anyways

**Comment by jimdebeer** [comment]
ok forget my previous comment --- best is to have the style requirable

**Comment by jimdebeer** [comment]
@DanilloCorvalan lets have a call today at 1400 to address vpack etc

**Comment by youzi** [comment]
The problem is most probably this:
- The lessloader compiles the less files (handling imports) before concatenating the files into a bundle.css, thus the imports are already handled before concatenating
----> solution: concatenate the less files before handling the imports

**Comment by DanilloCorvalan** [comment]
@jimdebeer sure thing man!

**Comment by DanilloCorvalan** [comment]
@youzi @nikoloza I asked at stack overflow if anyone have ever experienced this problem.
http://stackoverflow.com/questions/36130555/webpack-less-loader-override-variables-for-node-modules

We have a potential solution for it I think (Bob Sponge answer)
