### ISSUE TITLE
[build] Building doesn't remove comments

### ISSUE THREAD

**Issue by youzi** [vigour-io/vpack#29]
So our current builds include some MIT licences etc. Building should remove all comments.

**Comment by shawninder** [comment]
I'm not sure that's legal actually, which is why minification tools have learned to leave those comments in by default. Perhaps we could remove them all on native devices (where looking at the source code is an uncommon use-case and where leaving the comments in may decrease performance) by providing the correct options to our minifiers (see http://stackoverflow.com/a/17469783/157949). But on the web I think we may be legally obliged to preserve the comments. https://hypothes.is/a/AVO3XQMDH9ZO4OKSlaNO

**Comment by jimdebeer** [comment]
you can create a licenses file i think (i saw this a few times) and them make a reference to that license file from the comments -- not 100% sure though lets ask joost
